from __future__ import annotations
import collections.abc
import noder.core
import typing
__all__: list[str] = ['Base', 'Tree', 'Zone', 'new_base', 'new_zone_from_arrays']
class Base(noder.core.Node):
    """
    
    CGNS Base helper built on top of :py:class:`noder.core.Node`.
    
    This class provides treelab-inspired zone aggregation helpers.
    """
    def __init__(self, name: str = 'Base') -> None:
        ...
    def all_fields(self, include_coordinates: bool = True, return_type: str = 'dict', ravel: bool = False, append_container_to_field_name: bool = False) -> typing.Any:
        ...
    def assert_fields_size_coherency(self) -> None:
        ...
    def dim(self) -> int:
        ...
    def fields(self, field_names: typing.Any, container: str = 'FlowSolution', behavior_if_not_found: str = 'create', dtype: typing.Any = 'float64', return_type: str = 'dict', ravel: bool = False) -> typing.Any:
        ...
    def get_elements_types(self) -> list[str]:
        ...
    def is_hybrid(self) -> bool:
        ...
    def is_structured(self) -> bool:
        ...
    def is_unstructured(self) -> bool:
        ...
    def new_fields(self, input_fields: typing.Any, container: str = 'FlowSolution', grid_location: str = 'auto', dtype: typing.Any = 'float64', return_type: str = 'dict', ravel: bool = False) -> typing.Any:
        ...
    def number_of_cells(self) -> int:
        ...
    def number_of_points(self) -> int:
        ...
    def number_of_zones(self) -> int:
        ...
    def physical_dimension(self) -> int:
        ...
    def remove_empty_zones(self) -> None:
        ...
    def set_cell_dimension(self, cell_dimension: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_physical_dimension(self, physical_dimension: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def update_dimensions_from_zones(self) -> None:
        ...
    def zones(self) -> list[Zone]:
        ...
class Tree(noder.core.Node):
    """
    
    CGNS Tree helper built on top of :py:class:`noder.core.Node`.
    
    This class provides treelab-inspired base and zone aggregation helpers.
    """
    def __init__(self) -> None:
        ...
    def add(self, node: noder.core.Node) -> None:
        ...
    def all_fields(self, include_coordinates: bool = True, return_type: str = 'dict', ravel: bool = False, append_container_to_field_name: bool = False) -> typing.Any:
        ...
    def assert_fields_size_coherency(self) -> None:
        ...
    def base(self, name: str) -> Base:
        ...
    def base_names(self) -> list[str]:
        ...
    def bases(self) -> list[Base]:
        ...
    def fields(self, field_names: typing.Any, container: str = 'FlowSolution', behavior_if_not_found: str = 'create', dtype: typing.Any = 'float64', return_type: str = 'dict', ravel: bool = False) -> typing.Any:
        ...
    def get_elements_types(self) -> list[str]:
        ...
    def is_hybrid(self) -> bool:
        ...
    def is_structured(self) -> bool:
        ...
    def is_unstructured(self) -> bool:
        ...
    def new_fields(self, input_fields: typing.Any, container: str = 'FlowSolution', grid_location: str = 'auto', dtype: typing.Any = 'float64', return_type: str = 'dict', ravel: bool = False) -> typing.Any:
        ...
    def number_of_bases(self) -> int:
        ...
    def number_of_cells(self) -> int:
        ...
    def number_of_points(self) -> int:
        ...
    def number_of_zones(self) -> int:
        ...
    def remove_empty_zones(self) -> None:
        ...
    def set_unique_base_names(self) -> None:
        ...
    def set_unique_zone_names(self) -> None:
        ...
    def zone_names(self) -> list[str]:
        ...
    def zones(self) -> list[Zone]:
        ...
class Zone(noder.core.Node):
    """
    
    CGNS Zone helper built on top of :py:class:`noder.core.Node`.
    
    This class provides treelab-inspired field and geometry helpers.
    Not implemented on purpose: ``save`` and ``useEquation``.
    """
    def __init__(self, name: str = 'Zone') -> None:
        ...
    def all_fields(self, include_coordinates: bool = True, return_type: str = 'dict', ravel: bool = False, append_container_to_field_name: bool = False) -> typing.Any:
        ...
    def assert_fields_size_coherency(self) -> None:
        ...
    def boundaries(self) -> list[Zone]:
        ...
    def boundary(self, index: str = 'i', bound: str = 'min') -> Zone:
        ...
    def dim(self) -> int:
        ...
    def field(self, field_name: str, container: str = 'FlowSolution', behavior_if_not_found: str = 'create', dtype: typing.Any = 'float64', ravel: bool = False) -> typing.Any:
        ...
    def fields(self, field_names: typing.Any, container: str = 'FlowSolution', behavior_if_not_found: str = 'create', dtype: typing.Any = 'float64', return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def get_array_shapes(self) -> tuple[list[int], list[int]]:
        ...
    def get_elements_types(self) -> list[str]:
        ...
    def has_fields(self) -> bool:
        ...
    def imax(self) -> Zone:
        ...
    def imin(self) -> Zone:
        ...
    def infer_location(self, container: str) -> str:
        ...
    def is_empty(self) -> bool:
        ...
    def is_structured(self) -> bool:
        ...
    def is_unstructured(self) -> bool:
        ...
    def jmax(self) -> Zone:
        ...
    def jmin(self) -> Zone:
        ...
    def kmax(self) -> Zone:
        ...
    def kmin(self) -> Zone:
        ...
    def new_fields(self, input_fields: typing.Any, container: str = 'FlowSolution', grid_location: str = 'auto', dtype: typing.Any = 'float64', return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def number_of_cells(self) -> int:
        ...
    def number_of_points(self) -> int:
        ...
    def remove_fields(self, field_names: typing.Any, container: str = 'FlowSolution') -> None:
        ...
    def shape(self) -> list[int]:
        ...
    def shape_of_coordinates(self) -> list[int]:
        ...
    def update_shape(self) -> None:
        ...
    def x(self, ravel: bool = False) -> typing.Any:
        ...
    def xy(self, return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def xyz(self, return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def xz(self, return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def y(self, ravel: bool = False) -> typing.Any:
        ...
    def yz(self, return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def z(self, ravel: bool = False) -> typing.Any:
        ...
def new_base(name: str, zones: collections.abc.Sequence[Zone]) -> Base:
    """
    Construct a CGNSBase_t node from a list of zones.
    
    The base dimensions are inferred from the zones and must be coherent across
    all provided zones.
    """
def new_zone_from_arrays(name: str, array_names: collections.abc.Sequence[str], arrays: typing.Any) -> Zone:
    """
    Construct a structured CGNS Zone from a sequence of array names and arrays.
    
    Coordinate shortcuts ``x``, ``y`` and ``z`` are mapped to
    ``CoordinateX``, ``CoordinateY`` and ``CoordinateZ``. Other arrays are placed
    in ``FlowSolution``.
    """
