from __future__ import annotations
import noder.core
import typing
__all__: list[str] = ['Zone']
class Zone(noder.core.Node):
    """
    
    CGNS Zone helper built on top of :py:class:`noder.core.Node`.
    
    This class provides treelab-inspired field and geometry helpers.
    Not implemented on purpose: ``save`` and ``useEquation``.
    """
    def __init__(self, name: str = 'Zone') -> None:
        ...
    def all_fields(self, include_coordinates: bool = True, return_type: str = 'dict', ravel: bool = False, append_container_to_field_name: bool = False) -> typing.Any:
        ...
    def assert_fields_size_coherency(self) -> None:
        ...
    def boundaries(self) -> list[Zone]:
        ...
    def boundary(self, index: str = 'i', bound: str = 'min') -> Zone:
        ...
    def dim(self) -> int:
        ...
    def field(self, field_name: str, container: str = 'FlowSolution', behavior_if_not_found: str = 'create', dtype: typing.Any = 'float64', ravel: bool = False) -> typing.Any:
        ...
    def fields(self, field_names: typing.Any, container: str = 'FlowSolution', behavior_if_not_found: str = 'create', dtype: typing.Any = 'float64', return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def get_array_shapes(self) -> tuple[list[int], list[int]]:
        ...
    def get_elements_types(self) -> list[str]:
        ...
    def has_fields(self) -> bool:
        ...
    def imax(self) -> Zone:
        ...
    def imin(self) -> Zone:
        ...
    def infer_location(self, container: str) -> str:
        ...
    def is_empty(self) -> bool:
        ...
    def is_structured(self) -> bool:
        ...
    def is_unstructured(self) -> bool:
        ...
    def jmax(self) -> Zone:
        ...
    def jmin(self) -> Zone:
        ...
    def kmax(self) -> Zone:
        ...
    def kmin(self) -> Zone:
        ...
    def new_fields(self, input_fields: typing.Any, container: str = 'FlowSolution', grid_location: str = 'auto', dtype: typing.Any = 'float64', return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def number_of_cells(self) -> int:
        ...
    def number_of_points(self) -> int:
        ...
    def remove_fields(self, field_names: typing.Any, container: str = 'FlowSolution') -> None:
        ...
    def shape(self) -> list[int]:
        ...
    def shape_of_coordinates(self) -> list[int]:
        ...
    def update_shape(self) -> None:
        ...
    def x(self, ravel: bool = False) -> typing.Any:
        ...
    def xy(self, return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def xyz(self, return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def xz(self, return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def y(self, ravel: bool = False) -> typing.Any:
        ...
    def yz(self, return_type: str = 'list', ravel: bool = False) -> typing.Any:
        ...
    def z(self, ravel: bool = False) -> typing.Any:
        ...
